import Head from 'next/head'
import { useContext } from 'react'

//contexts
import { Context as ThemeContext } from 'contexts/themeContext'

//components
import ToggleButton from 'components/toggleButton'

//styles
import { Main } from 'styles/main'
import { Title } from 'styles/title'
import { Form } from 'styles/form'

export default function Home() {
  const { theme, toggle } = useContext(ThemeContext)

  return (
    <div>
      <Head>
        <title>Dark mode test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          <h1>Dark mode toggle test</h1>
          <h3>Actual theme: {theme}</h3>
          <ToggleButton onClick={toggle} />
        </Title>
        <h2>This page is for test dark mode with styled components</h2>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, soluta
          esse <strong>rerum accusamus vero commodi aperiam</strong> numquam
          temporibus ipsum harum magni. Enim deserunt est ipsam, assumenda
          perferendis earum sapiente rem!
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, soluta
          esse rerum accusamus vero commodi aperiam numquam temporibus ipsum
          harum magni.{' '}
          <strong>
            Enim deserunt est ipsam, assumenda perferendis earum sapiente rem!
          </strong>
        </p>
        <Form>
          <label htmlFor="text"></label>
          <input id="text" type="text" placeholder="Put text here" />
          <input id="text" type="password" placeholder="Put text here" />
          <button type="button">lorem</button>
        </Form>
      </Main>
    </div>
  )
}
